### ISSUE TITLE
Example of LIPS + Preact

### ISSUE THREAD

**Issue by jcubic** [schemeweb/wiki#1]
I'm not able to edit the Wiki, but here is an example code that uses SXML with Preact.js application that works out of the box, you don't need any front-end Scheme framework. With LIPS you can use any JavaScript framework you want.

https://codepen.io/jcubic/pen/JjKbqWd?editors=1000

Here is the code:
```scheme
(define Component preact.Component)
(define render preact.render)
(define h preact.h)

;; The example use SXML syntax https://en.wikipedia.org/wiki/SXML

(define-class Button1 Component
	(render (lambda (self props state)
			   (sxml (button (@ (onClick (lambda (e)
                                            (alert "Hello class Component"))))
                                   props.name)))))

(define (Button2 props)
  (sxml (button (@ (onClick (lambda ()
                              (alert "Hello function component"))))
                props.name)))

(render (sxml (div (@ (id "foo"))
                   (p "Hello World")
                   (Button1 (@ (name "me")))
                   (Button2 (@ (name "me")))))
        document.body)
```

By default sxml macro use `h` from Preact. To make it work with React.js you will need to generate new sxml macro with `pragma->sxml` macro.

**Comment by lassik** [comment]
Excellent. I added you to the schemeweb organization so you can now edit wikis and push commits directly.

**Comment by jcubic** [comment]
Thanks.
